import os

#MONGODB_HOST = os.getenv("MONGODB_PORT_27017_TCP_ADDR", "localhost")
#MONGODB_PORT = int(os.getenv("MONGODB_PORT_27017_TCP_PORT", "27017"))
#MONGODB_DB = "pkgdb"
SECRET_KEY = "DO NOT USE THIS IN PRODUCTION!"
ADMIN_USERNAME = "admin"
ADMIN_PASSWORD = "admin"